### ISSUE TITLE
update imageregister defaultRoute will make openshift api restart.

### ISSUE THREAD

**Issue by hchenxa** [openshift/cluster-openshift-apiserver-operator#316] opened 2020-02-21 08:01 UTC
See the summary above, after enable/disable the imageregistry defaultRoute, the openshift apiserver will be restart.

```
[root@ocp420219wtj-inf ~]# oc patch configs.imageregistry.operator.openshift.io/cluster --type merge -p '{"spec":{"defaultRoute":false}}'
config.imageregistry.operator.openshift.io/cluster patched
[root@ocp420219wtj-inf ~]# oc get pods -n openshift-apiserver
NAME              READY   STATUS    RESTARTS   AGE
apiserver-rgcfb   1/1     Running   0          46h
[root@ocp420219wtj-inf ~]# oc get pods -n openshift-apiserver
NAME              READY   STATUS        RESTARTS   AGE
apiserver-rgcfb   1/1     Terminating   0          46h
[root@ocp420219wtj-inf ~]# oc get pods -n openshift-apiserver
NAME              READY   STATUS    RESTARTS   AGE
apiserver-bpd2l   0/1     Pending   0          1s
[root@ocp420219wtj-inf ~]# oc get pods -n openshift-apiserver
NAME              READY   STATUS     RESTARTS   AGE
apiserver-bpd2l   0/1     Init:0/1   0          2s
[root@ocp420219wtj-inf ~]# oc get pods -n openshift-apiserver
error: You must be logged in to the server (Unauthorized)
[root@ocp420219wtj-inf ~]# oc get pods -n openshift-apiserver
error: You must be logged in to the server (Unauthorized)
[root@ocp420219wtj-inf ~]# oc get pods -n openshift-apiserver
error: You must be logged in to the server (Unauthorized)
[root@ocp420219wtj-inf ~]# oc get pods -n openshift-apiserver
error: You must be logged in to the server (Unauthorized)
[root@ocp420219wtj-inf ~]# oc get pods -n openshift-apiserver
error: You must be logged in to the server (Unauthorized)
```

**Comment by hchenxa** [comment] 2020-02-21 08:25
and the root cause was the imagepolicyconfig was in openshift-apiserver configmap, so when update the defaultRoute, it will update the configmap in openshift-apiserver as well which will make operator to restart the openshift-apiserver.

**Comment by sttts** [comment] 2020-02-24 09:39
So this was intended and this issue can be closed as it is not a bug?

**Comment by sttts** [comment] 2020-02-24 09:40
cc @adambkaplan

**Closed** 2020-11-29 15:26 UTC
Labels: lifecycle/rotten
